export const TAXES_REQUESTED = 'TAXES_REQUESTED'
export const TAXES_OK = 'TAXES_OK'
export const TAXES_ERROR = 'TAXES_ERROR'

export const SUBMISSION_FORM_REQUESTED = 'SUBMISSION_FORM_REQUESTED'
export const SUBMISSION_FORM_OK = 'SUBMISSION_FORM_OK'
export const SUBMISSION_FORM_ERROR = 'SUBMISSION_FORM_ERROR'

export const SUBMISSION_CREATE_REQUESTED = 'SUBMISSION_CREATE_REQUESTED'
export const SUBMISSION_CREATE_OK = 'SUBMISSION_CREATE_OK'
export const SUBMISSION_CREATE_ERROR = 'SUBMISSION_CREATE_ERROR'

export const SUBMISSION_DELETE_REQUESTED = 'SUBMISSION_DELETE_REQUESTED'
export const SUBMISSION_DELETE_OK = 'SUBMISSION_DELETE_OK'
export const SUBMISSION_DELETE_ERROR = 'SUBMISSION_DELETE_ERROR'

export const SUBMISSION_UPDATE_REQUESTED = 'SUBMISSION_UPDATE_REQUESTED'
export const SUBMISSION_UPDATE_OK = 'SUBMISSION_UPDATE_OK'
export const SUBMISSION_UPDATE_ERROR = 'SUBMISSION_UPDATE_ERROR'