export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED'
export const LOGIN_USER_OK = 'LOGIN_USER_OK'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGOUT_USER_OK = 'LOGOUT_USER_OK'
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR'